spring.application.name=tache

# Profil par défaut : PostgreSQL
spring.profiles.active=postgres

# Configuration Hibernate / JPA commune
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

